### ISSUE TITLE
Include a usage example in the readme 

### ISSUE THREAD

**Issue by addyosmani** [joefiorini/grunt-es6-module-transpiler#1]
Great work on the wrapper. One thing that would greatly help developers trying to get started is a usage example that starts with creating a transpiler compatible module, modifying your grunt file and then building/transpiling. Could you add that?

**Comment by joefiorini** [comment]
Thanks! I recently noticed I overlooked that, I will get one added very soon!

**Comment by joefiorini** [comment]
Done, please let me know if there's anything I missed.

**Comment by addyosmani** [comment]
That's fantastic. I just went through your changes - great work. I'll going to call out this project in my next article. I think a number of developers will find it of interest.

**Comment by joefiorini** [comment]
Great, thank you!

**Comment by leshill** [comment]
:+1:
